### ISSUE TITLE
Error when editing my contribution

### ISSUE THREAD

**Issue by fruether** [101companies/101rails#199]
I am not able to add a tripple store to my contribution because the saving process is giving an error. 

Consider for example my 101kafka contribution: https://101wiki.softlang.org/Contribution:101kafka

Assume now that I want to edit this contribution created by me: 

- https://101wiki.softlang.org/Contribution:101kafka/edit

<img width="1000" alt="bildschirmfoto 2017-06-16 um 14 47 16" src="https://user-images.githubusercontent.com/1591040/27227184-bd8fd374-52a2-11e7-885b-a48308088ea4.png">

The change I want to make is to add a _"New Triple_". This is done by clicking on the corresponding Button
<img width="871" alt="bildschirmfoto 2017-06-16 um 14 48 41" src="https://user-images.githubusercontent.com/1591040/27227279-2348c7fc-52a3-11e7-9f55-a1437dda8667.png">

After the change was performed I click on _Save_. The result of this action is that the changes are not saved and I get a "Page not found" error:

<img width="961" alt="bildschirmfoto 2017-06-16 um 14 49 48" src="https://user-images.githubusercontent.com/1591040/27227395-9780c66a-52a3-11e7-9dde-f439757d1788.png">

@MarcelH91 @kevin-klein Can you verify that you two are as well not able to save an edited page?

**Comment by kevin-klein** [comment]
hard to say, for me it is working, you also have the same role as i do and when i use your user on my machine it is working too. does this problem also appear if you just save the page without changing anything?

**Comment by fruether** [comment]
It also appears when I save the page without changing anything. This is the case when I use as browser Safari or Chrome

**Comment by fruether** [comment]
The following message is shown as well when I open the 101kafa contribution:

<img width="519" alt="bildschirmfoto 2017-06-20 um 15 09 25" src="https://user-images.githubusercontent.com/1591040/27334726-7fc6a470-55ca-11e7-832e-cc3b858f484a.png">

**Comment by MarcelH91** [comment]
I just verified it.

**Comment by rlaemmel** [comment]
Is this all solved now?
Maybe, this has something today with Frederik not having much editing rights?

**Comment by fruether** [comment]
It is not fixed for me. I just retried the process. However, I noticed that I get an error message before I get redirected to the described error. That error message is saying:

> Sorry, you are not permitted to execute the last action
Afterwards I get redirected with the error described earlier.

The problem also appears for Marcel as he said. So we both seem to have a lack of privileges

**Comment by MarcelH91** [comment]
I can edit things there, now, but I don't know why Frederik can't.

**Comment by fruether** [comment]
I just made a screenshot of the error message that I am getting before I get redirected to the wiki page

<img width="637" alt="bildschirmfoto 2017-07-13 um 13 42 31" src="https://user-images.githubusercontent.com/1591040/28164787-3acd2a88-67d1-11e7-9adf-7cfb7de34ebc.png">

**Comment by kevin-klein** [comment]
i think it might have been a feedback issue, does it work for you now?

**Comment by fruether** [comment]
Hi @kevin-klein,

now I am not able to test it since a "Save" or "Edit" button for the contribution is missing when I open it edit mode. (Assuming I am not not to tired to see it). I am using Mac OSX and Chrome.

<img width="1223" alt="bildschirmfoto 2017-07-28 um 00 38 18" src="https://user-images.githubusercontent.com/1591040/28695036-28000d0a-732d-11e7-8b0b-05920034b2ff.png">

**Comment by kevin-klein** [comment]
that was what i assumed, you are not logged in it seems so you dont have
the rights.

2017-07-28 0:40 GMT+02:00 Frederik Ruether <notifications@github.com>:

**Comment by fruether** [comment]
Well I am as much logged in as I can be. After all the webpage indicates that I am logged in with my GitHub account fruether:
<img width="550" alt="bildschirmfoto 2017-07-28 um 13 21 06" src="https://user-images.githubusercontent.com/1591040/28715342-ad4763f4-7397-11e7-8c3b-e1a3f786172f.png">

So what do you @MarcelH91 suggest. Either I get the privs to be able to edit my contributions so that I am able to add the metadata (as they are described by the mega models of the seminar) or I will leave it as an open issue for some point in the future?

**Comment by kevin-klein** [comment]
You should absolutely have admin rights. Fruether is your github account used for 101wiki, isnt it? 
![fireshot capture 2 - contribution_101kafka - http___localhost_3000_contribution_101kafka](https://user-images.githubusercontent.com/3279763/28744051-68ff09dc-7459-11e7-9a99-da2671ea8905.png)
It looks like this for me when i log in as your user as of a dump from just now and editing a contribution works too for me.

**Comment by fruether** [comment]
@kevin-klein it is working for me now =) Thanks for fixing it
